# Generated by Django 4.2.21 on 2025-06-08 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_contabancaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='numero_conta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
