# Generated by Django 4.2.21 on 2025-06-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_contabancaria_numero_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='numero_conta',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='numero_cont',
            field=models.CharField(default='E218601BD7', max_length=10, unique=True),
        ),
    ]
