# Generated by Django 4.2.21 on 2025-06-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_remove_contabancaria_numero_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='numero_cont',
        ),
    ]
