# Generated by Django 5.2.1 on 2025-05-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'ordering': ['id'], 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='numero_conta',
        ),
    ]
